### ISSUE TITLE
Race Condition on Startup for Editor

### ISSUE THREAD

**Issue by hostilefork** [IngoHohmann/rebol-web-scripts#1]
Periodically when trying to run the editor, it will say:

    >> do https://raw.githubusercontent.com/IngoHohmann/rebol-web-scripts/master/editor.r
    (i) Info: use WHY for error information
    ** Error: ReferenceError: aceEditor is not defined
    ** Where: jsedit if edit do catch either else _ do main
    ** Near: [
        jsedit src ~~]
    ** File: https://raw.githubusercontent.com/IngoHohmann/rebol-web-scripts/master/editor.r
    ** Line: 121

**Comment by IngoHohmann** [comment]
I hope that cf1db81c3e1f10427d5540014fd5094b428dd718 helps with this.

**Comment by hostilefork** [comment]
Appears to work (though editor requires REDBOL apparently, e.g. mentions NUMBER!).

Closing this for now...
